### ISSUE TITLE
Compilation onto specific device

### ISSUE THREAD

**Issue by rexxy-sasori** [mafaneh/ble-ebook-project#4]
Can I compile any of the examples onto SEEED Tiny BLE platform ? If doing so is possible, could you please give me some help on how?

**Comment by mafaneh** [comment]
I looked at the SEEED Tiny BLE module and it's based on the nRF51822, so the examples will not work out of the box with this chipset (since the projects were created for the nRF52840 chipset). However, if you do get the examples migrated to the nRF51822 chipset, it seems you'd be able to simply drag and drop the hex files (for both the SoftDevice and Application) to the mounted (Tiny BLE) drive on your computer and it should flash the chipset.
